const artists: TSI_Artist[] = [
  {
    easyId: "bruegel-pte",
    imageMaxWidth: 2205,
    imageMaxHeight: 2640,
    imageOptWidth: 1604,
    imageOptHeight: 1920,
    imageThmWidth: 401,
    imageThmHeight: 480,
    name: "Pieter Bruegel the Elder",
    nationality: "Dutch",
    wikiPage: "https://en.wikipedia.org/wiki/Pieter_Bruegel_the_Elder",
  },
  {
    easyId: "cezanne",
    imageMaxWidth: 2589,
    imageMaxHeight: 3554,
    imageOptWidth: 1399,
    imageOptHeight: 1920,
    imageThmWidth: 350,
    imageThmHeight: 480,
    name: "Paul Cézanne",
    nationality: "French",
    wikiPage: "https://en.wikipedia.org/wiki/Paul_C%C3%A9zanne",
  },
  {
    easyId: "eakins",
    imageMaxWidth: 2530,
    imageMaxHeight: 3040,
    imageOptWidth: 1598,
    imageOptHeight: 1920,
    imageThmWidth: 399,
    imageThmHeight: 480,
    name: "Thomas Eakins",
    nationality: "American",
    wikiPage: "https://en.wikipedia.org/wiki/Thomas_Eakins",
  },
  {
    easyId: "friedrich",
    imageMaxWidth: 1443,
    imageMaxHeight: 1871,
    imageOptWidth: 1443,
    imageOptHeight: 1871,
    imageThmWidth: 370,
    imageThmHeight: 480,
    name: "Caspar David Friedrich",
    nationality: "German",
    wikiPage: "https://en.wikipedia.org/wiki/Caspar_David_Friedrich",
  },
  {
    easyId: "gauguin",
    imageMaxWidth: 3237,
    imageMaxHeight: 4000,
    imageOptWidth: 1554,
    imageOptHeight: 1920,
    imageThmWidth: 388,
    imageThmHeight: 480,
    name: "Paul Gauguin",
    nationality: "French",
    wikiPage: "https://en.wikipedia.org/wiki/Paul_Gauguin",
  },
  {
    easyId: "heade",
    imageMaxWidth: 378,
    imageMaxHeight: 473,
    imageOptWidth: 378,
    imageOptHeight: 473,
    imageThmWidth: 384,
    imageThmHeight: 480,
    name: "Martin Johnson Heade",
    nationality: "American",
    wikiPage: "https://en.wikipedia.org/wiki/Martin_Johnson_Heade",
  },
  {
    easyId: "homer",
    imageMaxWidth: 1129,
    imageMaxHeight: 1564,
    imageOptWidth: 1129,
    imageOptHeight: 1564,
    imageThmWidth: 346,
    imageThmHeight: 480,
    name: "Winslow Homer",
    nationality: "American",
    wikiPage: "https://en.wikipedia.org/wiki/Winslow_Homer",
  },
  {
    easyId: "manet",
    imageMaxWidth: 1824,
    imageMaxHeight: 2229,
    imageOptWidth: 1571,
    imageOptHeight: 1920,
    imageThmWidth: 393,
    imageThmHeight: 480,
    name: "Édouard Manet",
    nationality: "French",
    wikiPage: "https://en.wikipedia.org/wiki/%C3%89douard_Manet",
  },
  {
    easyId: "rousseau",
    imageMaxWidth: 843,
    imageMaxHeight: 1082,
    imageOptWidth: 843,
    imageOptHeight: 1082,
    imageThmWidth: 374,
    imageThmHeight: 480,
    name: "Henri Rousseau",
    nationality: "French",
    wikiPage: "https://en.wikipedia.org/wiki/Henri_Rousseau",
  },
  {
    easyId: "seurat",
    imageMaxWidth: 1148,
    imageMaxHeight: 1778,
    imageOptWidth: 1148,
    imageOptHeight: 1778,
    imageThmWidth: 310,
    imageThmHeight: 480,
    name: "Georges Seurat",
    nationality: "French",
    wikiPage: "https://en.wikipedia.org/wiki/Georges_Seurat",
  },
  {
    easyId: "sorolla",
    imageMaxWidth: 1406,
    imageMaxHeight: 1949,
    imageOptWidth: 1385,
    imageOptHeight: 1920,
    imageThmWidth: 346,
    imageThmHeight: 480,
    name: "Joaquín Sorolla",
    nationality: "Spanish",
    wikiPage: "https://en.wikipedia.org/wiki/Joaqu%C3%ADn_Sorolla",
  },
  {
    easyId: "vangogh",
    imageMaxWidth: 4747,
    imageMaxHeight: 6000,
    imageOptWidth: 1519,
    imageOptHeight: 1920,
    imageThmWidth: 380,
    imageThmHeight: 480,
    name: "Vincent van Gogh",
    nationality: "Dutch",
    wikiPage: "https://en.wikipedia.org/wiki/Vincent_van_Gogh",
  },
  {
    easyId: "vermeer",
    imageMaxWidth: 1016,
    imageMaxHeight: 1413,
    imageOptWidth: 1016,
    imageOptHeight: 1413,
    imageThmWidth: 345,
    imageThmHeight: 480,
    name: "Johannes Vermeer",
    nationality: "Dutch",
    wikiPage: "https://en.wikipedia.org/wiki/Johannes_Vermeer",
  },
  {
    easyId: "whistler",
    imageMaxWidth: 2841,
    imageMaxHeight: 3414,
    imageOptWidth: 1598,
    imageOptHeight: 1920,
    imageThmWidth: 399,
    imageThmHeight: 480,
    name: "James McNeill Whistler",
    nationality: "American",
    wikiPage: "https://en.wikipedia.org/wiki/James_Abbott_McNeill_Whistler",
  },
];

export { artists };
