import Link from "next/link";
import Head from "next/head";
import { Sty_Home } from "../styles/Home.sty";

export default function Home() {
  return (
    <Sty_Home className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <h1 className="title">Welcome to My Gallery</h1>

        <Link href="/gallery">
          <a>
            <picture>
              <source type="image/webp" srcSet="HERO_IMAGE.webp" />
              <source type="image/jpeg" srcSet="HERO_IMAGE.jpg" />
              <img
                src="HERO_IMAGE.jpg"
                alt="Wanderer above the Sea of Fog by Caspar David Friedrich"
              />
            </picture>
          </a>
        </Link>
        <Link href="/gallery">
          <a>Enter Gallery</a>
        </Link>

        <div className="grid">
          <a href="https://nextjs.org/docs" className="card">
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className="card">
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className="card"
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className="card"
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className="footer">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by Next.js
        </a>
      </footer>
    </Sty_Home>
  );
}
